### ISSUE TITLE
Simplify actions by using built-in conditional execution

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/devops#25]
Conditional execution has now been implemented for composite actions.

From <https://github.com/actions/runner/issues/834#issuecomment-961183560>

> Runner v2.284.0 and with it, conditional execution of composite actions is available across all hosted and self-hosted runners on github.com.

**Comment by mohawk2** [comment]
Is this something we'd really gain from? If not, is this done? :-)

**Comment by zmughal** [comment]
Not really. Just cleaner looking. And there would still be parts of the config where the conversion can not be done since the GitHub Actions runner evaluates at the wrong time.
